version: '3.0'

services:

  downloader:
    build: 
      context: ./
      dockerfile: ./Dockerfile_downloader
    command: 
      ["python", "-m", "downloader.py"]
    links:
      - redis01
    #depends_on: 
    #  - redis01

  redis01:
    image: redis:latest
#    ports:
#      - "6397:6397"
  
  redis-client:
    image: centos:7
    command: "ping redis01"
#    links: 
#      - redis01
