version: '3.0'

services:

  downloader:
    build: 
      context: ./
      dockerfile: ./Dockerfile_downloader
    command: 
      ["python", "-m", "downloader.py"]
    #links:
    #  - redis01
    depends_on: 
      - redis01

  redis01:
    image: redis:latest
    # port=6379
